language: python
python:
  - "3.5"
  - "3.6"
install:
  - ln -s SDK/Adafruit_DHT.py Adafruit_DHT.py
  - export include_beer_probe_device_base=./SDK/
  - pip install -r requirements.txt
script:
  - pytest test_brew_pri.py -s
  - pytest test_brew_sec.py -s
  - pytest test_probeTemp.py -s
notifications:
  # Disable email notifications for now
  email: false
