language: python
python:
  - "3.5"
  - "3.6"
install:
  - ln -s SDK/adafruit_dht.py adafruit_dht.py
  - export include_beer_probe_device_base=./SDK/
  - pip install -r SDK/requirements.txt
script:
  - pytest tests/
  - pytest modules/
notifications:
  # Disable email notifications for now
  email: false
