---
# default_defs stores the default definition of include-beer

INCLUDE_BEER_AMBIENT_PIN:
    name: GPIO Pin location of Ambient sensor data
    type: string
    default: 26
    description:
        - Usually is a number corresponding to GPIO pin
        - Can be set to Empty for local testing
    env: 
        - {name: INCLUDE_BEER_AMBIENT_PIN}
    ini: 
        - { key: ambient_pin, section: defaults}

INCLUDE_BEER_BASE_DIR:
    name: Base directory include-beer is installed in
    type: string
    default: ~/include-beer
    description:
        - Where include-beer repo/release has been installed
    env: 
        - {name: INCLUDE_BEER_BASE_DIR}
    ini: 
        - { key: base_dir, section: defaults}

INCLUDE_BEER_LOG_DIR:
    name: Location logs are written to
    type: string
    default: ~/include-beer/logs
    description:
        - Where include-beer logs are written to
    env: 
        - {name: INCLUDE_BEER_LOG_DIR}
    ini: 
        - { key: log_dir, section: defaults}

INCLUDE_BEER_DEBUG:
    name: If debug is enable or not
    type: boolean
    default: False
    description:
        - Set to True to enable debugging
    env: 
        - {name: INCLUDE_BEER_DEBUG}
    ini: 
        - { key: debug, section: defaults}
    
